spring.application.name=order-service

server.port=8083
rabbitmq.queue.order.name=order
rabbitmq.exchange.order.name=order_exchange
rabbitmq.routing.order.key=order_routingkey

rabbitmq.queue.email.name=email
rabbitmq.binding.routing.email.key=email_routingkey
